config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
    resources :lists do
      resources :bookmarks, only: [:new, :create]
    end

    resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :list
  belongs_to :movie

  validates :comment, presence: true, length: { minimum: 6 }

  validates :movie, uniqueness: { scope: :list }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_many :lists

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true, uniqueness: true
  # validates :poster_url, presence: true
  # validates :rating, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list, only: %i[new create]

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    @bookmark.list = @list
    if  @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end

  private

  def set_list
    @list = List.find(params[:list_id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:comment, :list_id, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def index
    @lists = List.all
  end

  def new
    @list = List.new
  end

  def show
  end

  def edit
  end

  def update
    @list.update(list_params)
    redirect_to list_path(@list)
  end

  def destroy
    @list.destroy
    redirect_to lists_path, status: :see_other
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end

  def set_list
    @list = List.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/new.html.erb
<%= simple_form_for [@list, @bookmark] do |f| %>
  <h1 class="lead">New Bookmark for <%=@list.id %>-<%= @list.name %></h1>
  <hr>
  <%= f.association :movie, label_method: :title, value_method: :id%>
  <%= f.input :comment %>
  <hr>
  <%= f.submit "Submit", class: "btn btn-primary" %>
<% end %>
<br>
<%= link_to "All the list", lists_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<div class="container">


<%= form_with model: list do |f| %>

<table class="table">
  <thead>
    <tr>
      <th scope="col">items</th>
      <th scope="col">details</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= f.label :name %></td>
      <td><%= f.text_field :name %> </td>
    </tr>
  </tbody>
  </table>
<%= f.submit %> | <%= link_to "All the list", lists_path %>
   <% end %>
  </div>

app/views/lists/edit.html.erb
<%= render "form", list: @list %>

app/views/lists/index.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item active" aria-current="page">Lists</li>
  </ol>
</nav>
<hr>

<h1>Your Movie List</h1>
<table class="table">
  <thead>
  <tr>
      <th scope="col">id</th>
      <th scope="col">Name</th>
      <th scope="col"></th>
  </tr>
  <% @lists.each do |list| %>
  <tr>
   <td>
      <%= list.id %>
   </td>
    <td>
      <%= link_to list.name, list_path(list) %> </td>
    <td>
      <%= link_to "Delete",list_path(list), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
    </td>
  </tr>
  <% end %>
  </tbody>
</table>

<br>
  <%= link_to "All", lists_path %> |
  <%= link_to "New list", new_list_path %>

</div>

app/views/lists/new.html.erb
<%= render "form", list: @list %>

app/views/lists/show.html.erb
<p class="lead"> Watch list Details </p>
<hr>
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col"> </th>
      <th scope="col"> </th>
    </tr>
   </thead>
   <tbody>
    <tr>
      <th scope="row"><%=@list.id %></th>
      <td><%= @list.name %></td>
      <td><%= link_to "Edit", edit_list_path(@list) %></td>
      <td><%= link_to "Delete",list_path(@list), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %></td>
    </tr>
  </tbody>
</table>

<p class="lead"> Bookmarks: </p>
<hr>
<table class="table">
 <thead>
   <tr>
      <th scope="col">@Movie</th>
      <th scope="col"></th>

</thead>
<% @list.bookmarks.each do |bookmark| %>
  <tbody>
  <td><strong>
  <%= bookmark.movie.title %></strong>
  <hr >
  <blockquote>
  <%= bookmark.movie.overview %></blockquote>
  <br>
  Comment:
  <div class="card card-body">
   <%= bookmark.comment %>
  </div>
    <td><%= link_to "Delete?", bookmark_path(bookmark), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %></td>
    <%end%>
  </tbody>
</table>
<button type="button" class="btn btn-outline-primary">
<%= link_to 'Add Bookmark?',new_list_bookmark_path(@list) %></button> |
<%= link_to "All the list", lists_path %>